### ISSUE TITLE
Suggestion and general opinion on the actual needs

### ISSUE THREAD

**Issue by jrutgeer** [osrf/icra2023_ros2_gz_tutorial#10]
**Suggestion:**

https://github.com/osrf/icra2023_ros2_gz_tutorial/blob/a8259044852bc2b0d3a5f08e18153c0202fac726/README.md?plain=1#L126

The tutorials are nice, but show only a very limited subset of the functionality. So I suggest to also mention the [demos](https://github.com/ros2/examples) and [examples](https://github.com/ros2/examples) repositories.

</br>

**On a more general note:**

What I think is really really missing, both for ROS 2 as well as gazebo, is a general overview of the code base:
in depth descriptions of how the code is structured, which concepts are used, why, how, etc.
I.e. basic info that helps you understand the code.

This is an excellent example: [WaitSet Presentation at RTWG](https://drive.google.com/open?id=1I6caR6MrfQOUvylO4fFG_zHMW4J62u7k). It provides all the info you need to understand and use the code, yet it is concise and to the point. (Note that this video can only be found through this [github issue](https://github.com/ros2/rclcpp/pull/1047#issuecomment-731806325); afaik it is not part of, nor referenced by any official documentation, although it is very valuable.)

Same goes for gazebo. An example: as a layman try to debug why the [conveyor demo](https://github.com/gazebosim/gz-sim/blob/gz-sim7/examples/worlds/conveyor.sdf) is not working. So far, I tracked it down to the [contact plugin missing](https://github.com/gazebosim/gz-sim/blob/d2475ff905c31d27247d2d9e85f0d6a8f813e0e2/examples/worlds/empty.sdf#L80-L83) in the sdf, but then also [this entitycast failing](https://github.com/gazebosim/gz-sim/blob/8e10df665ba1c42ec37d64209d4cca4a337308b6/src/systems/physics/Physics.cc#L3828-L3832). So now I have to try and understand the reason for that. Without any background info on what an `entityWorldMap` is, how it is populated, etc., this utterly utterly time consuming. Most people just give up and [file an issue](https://github.com/gazebosim/gz-sim/issues/1662#issuecomment-1310866814) instead.

</br>

So even though this is probably (imo. falsely) considered out of scope for the icra tutorial, I think it would be far more valuable to the community, than yet another getting started session.

My two cents...

**Comment by jrutgeer** [comment]
> So far, I tracked it down to the contact plugin missing in the sdf, but then also [this entitycast failing](https://github.com/gazebosim/gz-sim/blob/8e10df665ba1c42ec37d64209d4cca4a337308b6/src/systems/physics/Physics.cc#L3828-L3832).

Turns out the contact plugin is not needed after all. 
The simulation features are defined [here](https://github.com/gazebosim/gz-physics/blob/ee36344af9e5049ee72e525d22e02b891cd863fa/dartsim/src/SimulationFeatures.hh#L54-L60) and [here](https://github.com/gazebosim/gz-physics/blob/ee36344af9e5049ee72e525d22e02b891cd863fa/dartsim/src/plugin.cc#L37-L49). 
So the conclusion is clear: it simply needs a [more recent version of libdart](https://github.com/gazebosim/gz-sim/issues/1662#issuecomment-1485840870).

But apart from that: I still don't understand how exactly above feature definitions relate to [the entitycast](https://github.com/gazebosim/gz-sim/blob/8e10df665ba1c42ec37d64209d4cca4a337308b6/src/systems/physics/Physics.cc#L3828-L3832). Though I am sure that it's no rocket science...

If ROS 2 / gazebo wants to welcome more user contributions for core functionality, then it is essential that this kind of information is better explained.

**Comment by clalancette** [comment]
> The tutorials are nice, but show only a very limited subset of the functionality. So I suggest to also mention the [demos](https://github.com/ros2/examples) and [examples](https://github.com/ros2/examples) repositories.

Yes, that is a great idea.  We won't add it to the outline that is here, but we'll make sure to add it to the slides.

> What I think is really really missing, both for ROS 2 as well as gazebo, is a general overview of the code base:
> in depth descriptions of how the code is structured, which concepts are used, why, how, etc.
> I.e. basic info that helps you understand the code.

Yes, we agree that would be valuable.  However, the target audience for this tutorial isn't people who are working deeply in the core, but rather people who want to use ROS 2 (and are coming from ROS 1), or Gazebo (and are coming from Gazebo Classic).  So while we will include e.g. a plugin walkthrough in Gazebo (which will cover the essential concepts), we will not be going into depth on these topics.

**Comment by mabelzhang** [comment]
Closing as no new activity for a month
