### ISSUE TITLE
Use less permissive way for Wayland than xhost plus

### ISSUE THREAD

**Issue by mabelzhang** [osrf/icra2023_ros2_gz_tutorial#11]
Currently, `run.bash` is using `xhost +` in order for Docker + Gazebo to work when using Wayland
https://github.com/osrf/icra2023_ros2_gz_tutorial/blob/a8259044852bc2b0d3a5f08e18153c0202fac726/docker/run.bash#L109

A less permissive way would be safer.
See http://wiki.ros.org/docker/Tutorials/GUI and https://github.com/gazebosim/docs/pull/356

**Comment by clalancette** [comment]
We tested this out, and it didn't work for us.  For now we are going to stick with the xhost +.
